# Generated by Django 4.2 on 2023-04-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Countdown', '0002_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prodLink',
            field=models.CharField(default='', max_length=200),
        ),
    ]
